# Site settings
title: Raphael Luckom
email: raphaelluckom@gmail.com
url: https://rluckom.github.io
description: "Software Engineer specializing in Python and JavaScript."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1c5e7d
  secondary: 4b2951
  secondary-dark: 34033d
  
# Footer settings
footer:
  copyright: Raphael Luckom
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/raphaelluckom
  - title: stack-overflow
    url: http://stackoverflow.com/users/2781226/tasteslikelemons
  - title: github
    url: http://github.com/rluckom

address:
    - line: Salem, MA

# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
